kind: pipeline
type: docker
name: galley
volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock
steps:
  - name: build cookbook
    image: node
    commands:
      - yarn --cwd cookbook install
      - yarn --cwd cookbook build
# further steps to come as other pieces are worked on