global:
  scrape_interval: 15s
  external_labels:
    monitor: 'galley-monitor'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'oven'
    scrape_interval: 1s
    static_configs:
      - targets: ['oven:8000']
